title: Primeros pasos en GitHub
description: >-
  ¿Acabas de registrarte? Éste es un buen lugar para empezar.
steps:
  - link: 'https://youtu.be/w3jLJU7DT5E'
    video: 'https://youtube.com/embed/w3jLJU7DT5E'
    title: ¿Qué es GitHub?
    description: >-
     Hey, es tu primera vez aquí, así que no presupongamos nada. Mira este
     breve video para entender por qué la gente usa GitHub.
  - course: introduccion-a-github
    description: >-
      El video está bien, ¿verdad? Si quieres aprender a usar el flujo de 
      trabajo descrito en el video, sigue este curso.
  - link: 'https://guides.github.com/introduction/git-handbook/'
    title: Manual de Git
    description: >-
      A estas alturas probablemente te estás preguntando qué es Git y por qué es
      importante para escribir código. Aquí tienes un breve artículo sobre 
      control de versiones con Git.
  - link: 'https://github.github.com/training-kit/downloads/es_ES/github-git-cheat-sheet/'
    title: Chuleta de Git
    description: >-
      Son muchas palabras y conceptos nuevos, ¿verdad? Esta chuleta te servirá de
      referencia rápida. Es útil que la tengas a mano (puedes imprimirla o guardarla
      en tus Marcadores).
  - course: comunicar-usando-markdown
    description: >-
      GitHub va sobre todo de colaboración, y colaboramos en _issues_ que forman 
      parte de _pull requests_. Aprende a transmitir lo que sabes con la sintaxis
      para formatear texto más fácil del mundo.
  - link: 'https://youtu.be/2MsN8gpT6jY'
    video: 'https://youtube.com/embed/2MsN8gpT6jY'
    title: Descubre GitHub Pages
    description: >-
      Lanzar un sitio web personal nunca fue tan fácil como con GitHub Pages.
      Mira este divertido video para aprender cómo puedes crear y alojar sitios
      web espectaculares y ¡gratuitos! en GitHub.
  - course: github-pages
    description: >-
      ¿Lista para crear tu propio sitio web con GitHub Pages? Este curso te 
      ayudará a crear tu primer sitio web en solo unos minutos.